<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dust</string>
	</array>
	<key>name</key>
	<string>Dust</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#yfm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_block_comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_block_start</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_block_end</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_partials</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_inline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dust_html_tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>dust_block_comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{!</string>
					<key>end</key>
					<string>\!}</string>
					<key>name</key>
					<string>comment.block.dust</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\s*(\&lt;)</string>
							<key>end</key>
							<string>\&gt;\s?</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dust_comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dust_block_end</key>
		<dict>
			<key>begin</key>
			<string>(\{~?/)([a-zA-Z0-9_\.-]+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.open.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.helper.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.closed.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.block.end.dust</string>
			<key>patterns</key>
			<array/>
		</dict>
		<key>dust_block_start</key>
		<dict>
			<key>begin</key>
			<string>(\{)(\+|\?|\^|\@|\#|\:|\&lt;)([-a-zA-Z0-9_\./]+)\s?(@?[-a-zA-Z0-9_\./]+)*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.delimiter.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.dust</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.helper.dust</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.generic.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.closed.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.block.start.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_html_tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_generic_attribute</string>
				</dict>
			</array>
		</dict>
		<key>dust_comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{!)\s(\{\@|\&lt;)</string>
					<key>end</key>
					<string>\!\}</string>
					<key>name</key>
					<string>comment.dust</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>-{2,3}\s*&gt;</string>
					<key>name</key>
					<string>comment.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>--</string>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dust_generic_attribute</key>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z0-9_-]+)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute.generic.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|"|)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
			</array>
		</dict>
		<key>dust_html_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9\-:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;(&lt;)/)(\2)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.scope.between-tag-pair.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#dust_tags</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dust_id_attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|"|)</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
			</array>
		</dict>
		<key>dust_inline</key>
		<dict>
			<key>begin</key>
			<string>\{\s*([-a-zA-Z0-9_\./\$]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.delimiter.dust</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.delimiter.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.delimiter.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.inline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_generic_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
			</array>
		</dict>
		<key>dust_partials</key>
		<dict>
			<key>begin</key>
			<string>(\{(&gt;))\s*([-a-zA-Z0-9_\.]+)*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.open.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.dust</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.helper.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\/\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.closed.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.block.start.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
			</array>
		</dict>
		<key>dust_string_double_quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_partials</string>
				</dict>
			</array>
		</dict>
		<key>dust_string_single_quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_partials</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
			</array>
		</dict>
		<key>dust_strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_string_single_quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_string_double_quoted</string>
				</dict>
			</array>
		</dict>
		<key>dust_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dust_id_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_generic_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_block_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dust_partials</string>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>escaped_double_quote</key>
		<dict>
			<key>match</key>
			<string>\\"</string>
			<key>name</key>
			<string>constant.character.escape.html</string>
		</dict>
		<key>escaped_single_quote</key>
		<dict>
			<key>match</key>
			<string>\\'</string>
			<key>name</key>
			<string>constant.character.escape.html</string>
		</dict>
		<key>yfm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\s)---\n$</string>
					<key>end</key>
					<string>^---\s</string>
					<key>name</key>
					<string>markup.raw.yaml.front-matter</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.yaml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.dust</string>
	<key>uuid</key>
	<string>d5e33b2e-ca20-40a8-bf55-8c16e32b04d4</string>
</dict>
</plist>
