<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dust</string>
	</array>
	<key>name</key>
	<string>Dust</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#yfm</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_helper</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_end</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#partial_and_var</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html_tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{!</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>comment.block.dust</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\s*(\&lt;)</string>
							<key>end</key>
							<string>\&gt;\s</string>
						</dict>
						<dict>
							<key>match</key>
							<string>@\w*</string>
							<key>name</key>
							<string>keyword.annotation.html</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\s*(\{)</string>
							<key>end</key>
							<string>\}\s</string>
						</dict>
						<dict>
							<key>match</key>
							<string>@\w*</string>
							<key>name</key>
							<string>keyword.annotation.dust</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block_end</key>
		<dict>
			<key>begin</key>
			<string>(\{~?/)([a-zA-Z0-9_\.-]+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.block.end.dust</string>
			<key>patterns</key>
			<array/>
		</dict>
		<key>block_helper</key>
		<dict>
			<key>begin</key>
			<string>(\{)(\+|\?|\^|\@|\#)([-a-zA-Z0-9_\./]+)\s?(@?[-a-zA-Z0-9_\./]+)*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.dust</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.dust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.block.start.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{!)\s(\{\@|\&lt;)</string>
					<key>end</key>
					<string>\!\}</string>
					<key>name</key>
					<string>comment.dust</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;!--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>-{2,3}\s*&gt;</string>
					<key>name</key>
					<string>comment.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>--</string>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>escaped-double-quote</key>
		<dict>
			<key>match</key>
			<string>\\"</string>
			<key>name</key>
			<string>constant.character.escape.js</string>
		</dict>
		<key>escaped-single-quote</key>
		<dict>
			<key>match</key>
			<string>\\'</string>
			<key>name</key>
			<string>constant.character.escape.js</string>
		</dict>
		<key>html_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9:-]+)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;(&lt;)/)(\2)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.scope.between-tag-pair.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag-stuff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>partial_and_var</key>
		<dict>
			<key>begin</key>
			<string>(\{~?(\+|\^|\&gt;|\#|\?)*)\s*(@?[-a-zA-Z0-9_\./]+)*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.dust</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.dust</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(~?\}*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.dust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.inline.other.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#helpers_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#helpers_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#partial_and_var</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.dust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#helpers_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#helpers_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#partial_and_var</string>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_id_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_generic_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#helpers_start</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#helpers_end</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#partial_and_var</string>
				</dict>
			</array>
		</dict>
		<key>tag_generic_attribute</key>
		<dict>
			<key>begin</key>
			<string>\b([a-zA-Z0-9_-]+)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.generic.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|"|)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>tag_id_attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|"|)</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>yfm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\s)---\n$</string>
					<key>end</key>
					<string>^---\s</string>
					<key>name</key>
					<string>markup.raw.yaml.front-matter</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.yaml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.dust</string>
	<key>uuid</key>
	<string>d5e33b2e-ca20-40a8-bf55-8c16e32b04d4</string>
</dict>
</plist>
